import * as THREE from 'three';

// Textures and shaders for the level 2 hub.
//
// The hub model is generated by code and has no UV coordinates, so ordinary image
// textures cannot be wrapped onto it. Instead the surfaces use TRIPLANAR MAPPING: the
// fragment shader works out each pixel's world position and projects the texture along
// the x, y and z axes, blending the three by how much the surface faces each way. Any
// shape gets tiled detail with no UV work, and the tile size is in metres.
//
// Two procedurally drawn textures (no image files, so they are ours and tiny):
//   plate  - riveted metal panels with seams, scratches, brushing and grime
//   floor  - tread plate: big panels with a diamond-bar tread
// Each has an albedo map (colour) and a height map. The height map drives BUMP MAPPING in
// the shader (it perturbs the surface normal, so the lights catch the rivets and seams)
// and the roughness (seams and grime are rougher, scratches shinier).
//
// The glowing materials get a second shader: light that flows through the strips.

const SIZE = 512;

// small deterministic random numbers so the textures look the same every run
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Draws everything wrapped, so the texture tiles without a visible edge
function wrapped(ctx, draw) {
  for (const ox of [-SIZE, 0, SIZE]) {
    for (const oy of [-SIZE, 0, SIZE]) draw(ox, oy);
  }
}

const gray = (v, a = 1) => `rgba(${Math.round(v * 255)},${Math.round(v * 255)},${Math.round(v * 255)},${a})`;

function paintNoise(ctx, amount, rand) {
  const img = ctx.getImageData(0, 0, SIZE, SIZE);
  const d = img.data;
  for (let i = 0; i < d.length; i += 4) {
    const n = (rand() - 0.5) * 255 * amount;
    d[i] += n; d[i + 1] += n; d[i + 2] += n;
  }
  ctx.putImageData(img, 0, 0);
}

// mode 'albedo' paints colour, mode 'height' paints relief (mid grey = flat)
function paintPlate(ctx, mode, seed) {
  const rand = rng(seed);
  const albedo = mode === 'albedo';
  ctx.fillStyle = albedo ? gray(0.62) : gray(0.55);
  ctx.fillRect(0, 0, SIZE, SIZE);

  // Each of the 2x2 panels is a slightly different shade
  for (let py = 0; py < 2; py++) {
    for (let px = 0; px < 2; px++) {
      const v = albedo ? 0.56 + rand() * 0.14 : 0.5 + rand() * 0.1;
      ctx.fillStyle = gray(v);
      ctx.fillRect(px * 256 + 3, py * 256 + 3, 250, 250);
    }
  }

  // Seams between panels (a dark groove with a thin highlight beside it)
  for (const c of [0, 256]) {
    ctx.strokeStyle = albedo ? gray(0.2) : gray(0.12);
    ctx.lineWidth = 4;
    wrapped(ctx, (ox, oy) => {
      ctx.beginPath(); ctx.moveTo(c + ox, oy); ctx.lineTo(c + ox, SIZE + oy); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(ox, c + oy); ctx.lineTo(SIZE + ox, c + oy); ctx.stroke();
    });
    ctx.strokeStyle = albedo ? gray(0.85, 0.5) : gray(0.85, 0.7);
    ctx.lineWidth = 1.5;
    wrapped(ctx, (ox, oy) => {
      ctx.beginPath(); ctx.moveTo(c + 4 + ox, oy); ctx.lineTo(c + 4 + ox, SIZE + oy); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(ox, c + 4 + oy); ctx.lineTo(SIZE + ox, c + 4 + oy); ctx.stroke();
    });
  }

  // Rivets: round heads along every panel edge
  const rivet = (x, y) => {
    wrapped(ctx, (ox, oy) => {
      ctx.fillStyle = albedo ? gray(0.2) : gray(0.95);
      ctx.beginPath(); ctx.arc(x + ox, y + oy, 5.2, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = albedo ? gray(0.78) : gray(1);
      ctx.beginPath(); ctx.arc(x + ox - 1, y + oy - 1, 2.6, 0, Math.PI * 2); ctx.fill();
    });
  };
  for (const cx of [0, 256]) {
    for (const cy of [0, 256]) {
      for (const [dx, dy] of [[16, 16], [-16, 16], [16, -16], [-16, -16], [64, 16], [-64, 16], [64, -16], [-64, -16], [16, 64], [16, -64], [-16, 64], [-16, -64]]) {
        rivet(cx + dx, cy + dy);
      }
    }
  }

  // Hatch plates and vents on some panels
  for (let i = 0; i < 3; i++) {
    const x = 40 + rand() * 180 + (rand() > 0.5 ? 256 : 0);
    const y = 60 + rand() * 120 + (rand() > 0.5 ? 256 : 0);
    const w = 50 + rand() * 40, h = 20 + rand() * 24;
    wrapped(ctx, (ox, oy) => {
      ctx.fillStyle = albedo ? gray(0.34) : gray(0.35);
      ctx.fillRect(x + ox, y + oy, w, h);
      ctx.strokeStyle = albedo ? gray(0.08) : gray(0.15);
      ctx.lineWidth = 2;
      ctx.strokeRect(x + ox, y + oy, w, h);
      for (let s = 6; s < h - 3; s += 5) {
        ctx.strokeStyle = albedo ? gray(0.12) : gray(0.1);
        ctx.beginPath(); ctx.moveTo(x + ox + 4, y + oy + s); ctx.lineTo(x + ox + w - 4, y + oy + s); ctx.stroke();
      }
    });
  }

  // Scratches
  for (let i = 0; i < 16; i++) {
    const x = rand() * SIZE, y = rand() * SIZE, len = 30 + rand() * 90, ang = rand() * Math.PI;
    ctx.strokeStyle = albedo ? gray(0.85, 0.12) : gray(0.3, 0.3);
    ctx.lineWidth = 2;
    wrapped(ctx, (ox, oy) => { ctx.beginPath(); ctx.moveTo(x + ox, y + oy); ctx.lineTo(x + ox + Math.cos(ang) * len, y + oy + Math.sin(ang) * len); ctx.stroke(); });
  }

  // Grime: dark soft blotches, heavier near the seams
  for (let i = 0; i < 7; i++) {
    const x = rand() * SIZE, y = rand() * SIZE, r = 30 + rand() * 80;
    wrapped(ctx, (ox, oy) => {
      const g = ctx.createRadialGradient(x + ox, y + oy, 0, x + ox, y + oy, r);
      g.addColorStop(0, albedo ? 'rgba(20,24,30,0.12)' : 'rgba(30,30,30,0.12)');
      g.addColorStop(1, 'rgba(0,0,0,0)');
      ctx.fillStyle = g;
      ctx.fillRect(x + ox - r, y + oy - r, r * 2, r * 2);
    });
  }
}

function paintFloor(ctx, mode, seed) {
  const rand = rng(seed);
  const albedo = mode === 'albedo';
  ctx.fillStyle = albedo ? gray(0.5) : gray(0.5);
  ctx.fillRect(0, 0, SIZE, SIZE);

  // A research-lab floor: large smooth tiles, each a slightly different shade, with fine
  // dark joints between them and the odd round service port
  const T = 128;
  for (let ty = 0; ty < SIZE / T; ty++) {
    for (let tx = 0; tx < SIZE / T; tx++) {
      const v = albedo ? 0.46 + rand() * 0.08 : 0.5;
      ctx.fillStyle = gray(v);
      ctx.fillRect(tx * T + 2, ty * T + 2, T - 4, T - 4);
      if (rand() < 0.12) {
        const cx = tx * T + T / 2, cy = ty * T + T / 2;
        ctx.strokeStyle = albedo ? gray(0.22) : gray(0.3);
        ctx.lineWidth = 5;
        ctx.beginPath(); ctx.arc(cx, cy, T * 0.28, 0, Math.PI * 2); ctx.stroke();
        ctx.fillStyle = albedo ? gray(0.34) : gray(0.42);
        ctx.beginPath(); ctx.arc(cx, cy, T * 0.2, 0, Math.PI * 2); ctx.fill();
      }
    }
  }
  for (let c = 0; c <= SIZE; c += T) {
    ctx.strokeStyle = albedo ? gray(0.16) : gray(0.2);
    ctx.lineWidth = 3;
    wrapped(ctx, (ox, oy) => {
      ctx.beginPath(); ctx.moveTo(c + ox, oy); ctx.lineTo(c + ox, SIZE + oy); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(ox, c + oy); ctx.lineTo(SIZE + ox, c + oy); ctx.stroke();
    });
  }

  // Very light scuffing, so it reads as used but clean
  for (let i = 0; i < 8; i++) {
    const x = rand() * SIZE, y = rand() * SIZE, r = 40 + rand() * 90;
    wrapped(ctx, (ox, oy) => {
      const g = ctx.createRadialGradient(x + ox, y + oy, 0, x + ox, y + oy, r);
      g.addColorStop(0, albedo ? 'rgba(20,24,30,0.1)' : 'rgba(40,40,40,0.08)');
      g.addColorStop(1, 'rgba(0,0,0,0)');
      ctx.fillStyle = g;
      ctx.fillRect(x + ox - r, y + oy - r, r * 2, r * 2);
    });
  }
}

// ---- Realistic surfaces for furniture and objects (the lab). Albedo maps sit around 0.69 grey,
// because the shader brightens them by 1.45: plain areas then keep the material's own colour.

function softBlobs(ctx, rand, n, rMin, rMax, colour) {
  for (let i = 0; i < n; i++) {
    const x = rand() * SIZE, y = rand() * SIZE, r = rMin + rand() * (rMax - rMin);
    wrapped(ctx, (ox, oy) => {
      const g = ctx.createRadialGradient(x + ox, y + oy, 0, x + ox, y + oy, r);
      g.addColorStop(0, colour);
      g.addColorStop(1, 'rgba(0,0,0,0)');
      ctx.fillStyle = g;
      ctx.fillRect(x + ox - r, y + oy - r, r * 2, r * 2);
    });
  }
}

function fineScratches(ctx, rand, n, colour, maxLen = 60) {
  ctx.strokeStyle = colour;
  ctx.lineWidth = 1;
  for (let i = 0; i < n; i++) {
    const x = rand() * SIZE, y = rand() * SIZE, len = 8 + rand() * maxLen, a = rand() * Math.PI;
    wrapped(ctx, (ox, oy) => { ctx.beginPath(); ctx.moveTo(x + ox, y + oy); ctx.lineTo(x + ox + Math.cos(a) * len, y + oy + Math.sin(a) * len); ctx.stroke(); });
  }
}

// powder-coated metal furniture: a fine orange-peel grain, faint wear and hairline scratches
function paintPaint(ctx, mode, seed) {
  const rand = rng(seed), albedo = mode === 'albedo';
  ctx.fillStyle = gray(albedo ? 0.69 : 0.5);
  ctx.fillRect(0, 0, SIZE, SIZE);
  paintNoise(ctx, albedo ? 0.05 : 0.22, rand);
  if (albedo) {
    softBlobs(ctx, rand, 6, 30, 90, 'rgba(255,255,255,0.05)');
    softBlobs(ctx, rand, 5, 20, 70, 'rgba(0,0,0,0.05)');
  }
  fineScratches(ctx, rand, 24, albedo ? 'rgba(255,255,255,0.12)' : 'rgba(40,40,40,0.5)');
}

// moulded plastic: almost smooth, a few smudges and fingerprints
function paintPlastic(ctx, mode, seed) {
  const rand = rng(seed), albedo = mode === 'albedo';
  ctx.fillStyle = gray(albedo ? 0.69 : 0.5);
  ctx.fillRect(0, 0, SIZE, SIZE);
  paintNoise(ctx, albedo ? 0.02 : 0.08, rand);
  softBlobs(ctx, rand, 10, 10, 45, albedo ? 'rgba(0,0,0,0.06)' : 'rgba(255,255,255,0.08)');
  fineScratches(ctx, rand, 10, albedo ? 'rgba(0,0,0,0.06)' : 'rgba(60,60,60,0.35)', 30);
}

// woven fabric: threads going over and under each other
function paintFabric(ctx, mode, seed) {
  const rand = rng(seed), albedo = mode === 'albedo';
  ctx.fillStyle = gray(albedo ? 0.6 : 0.35);
  ctx.fillRect(0, 0, SIZE, SIZE);
  const T = 16;
  for (let y = 0; y < SIZE; y += T) {
    for (let x = 0; x < SIZE; x += T) {
      const over = ((x + y) / T) % 2 === 0;
      const v = albedo ? 0.66 + rand() * 0.1 : 0.75;
      ctx.fillStyle = gray(v);
      if (over) ctx.fillRect(x + 1, y + 3, T - 2, T - 6);
      else ctx.fillRect(x + 3, y + 1, T - 6, T - 2);
    }
  }
  paintNoise(ctx, albedo ? 0.04 : 0.1, rand);
}

// printed paper: a header, rows of text, a small table and a chart
function paintPaper(ctx, mode, seed) {
  const rand = rng(seed), albedo = mode === 'albedo';
  ctx.fillStyle = gray(albedo ? 0.69 : 0.5);
  ctx.fillRect(0, 0, SIZE, SIZE);
  if (!albedo) return;
  const ink = (v) => gray(v * 0.69);
  ctx.fillStyle = ink(0.25);
  ctx.fillRect(40, 30, 220, 18);                                     // title
  ctx.fillRect(40, 56, 120, 8);
  for (let r = 0; r < 14; r++) {                                     // text lines made of words
    let x = 40;
    const y = 90 + r * 16;
    const end = r % 5 === 4 ? 260 : 470;
    while (x < end) {
      const w = 10 + rand() * 40;
      ctx.fillStyle = ink(0.35 + rand() * 0.1);
      ctx.fillRect(x, y, Math.min(w, end - x), 6);
      x += w + 6;
    }
  }
  ctx.strokeStyle = ink(0.35);                                       // a table
  ctx.lineWidth = 1.5;
  for (let r = 0; r <= 5; r++) { ctx.beginPath(); ctx.moveTo(40, 330 + r * 22); ctx.lineTo(280, 330 + r * 22); ctx.stroke(); }
  for (const c of [40, 120, 200, 280]) { ctx.beginPath(); ctx.moveTo(c, 330); ctx.lineTo(c, 440); ctx.stroke(); }
  ctx.beginPath();                                                    // a chart
  ctx.moveTo(310, 440); ctx.lineTo(310, 330); ctx.moveTo(310, 440); ctx.lineTo(470, 440); ctx.stroke();
  ctx.strokeStyle = 'rgba(40,70,150,0.8)';
  ctx.lineWidth = 2.5;
  ctx.beginPath();
  for (let i = 0; i <= 10; i++) { const x = 315 + i * 15, y = 420 - rand() * 80; i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }
  ctx.stroke();
}

// a printed bottle or box label: a dark band, text, hazard diamond and a barcode
function paintLabel(ctx, mode, seed) {
  const rand = rng(seed), albedo = mode === 'albedo';
  ctx.fillStyle = gray(albedo ? 0.69 : 0.5);
  ctx.fillRect(0, 0, SIZE, SIZE);
  if (!albedo) return;
  const ink = (v) => gray(v * 0.69);
  for (let k = 0; k < 2; k++) {
    const oy = k * 256;
    ctx.fillStyle = 'rgba(30,60,120,0.85)';
    ctx.fillRect(0, oy + 20, SIZE, 50);
    ctx.fillStyle = ink(0.95);
    ctx.fillRect(30, oy + 35, 160, 18);
    for (let r = 0; r < 5; r++) {
      ctx.fillStyle = ink(0.3);
      ctx.fillRect(30, oy + 90 + r * 18, 120 + rand() * 200, 7);
    }
    ctx.save();                                                        // hazard diamond
    ctx.translate(430, oy + 140); ctx.rotate(Math.PI / 4);
    ctx.strokeStyle = 'rgba(200,30,20,0.9)'; ctx.lineWidth = 6;
    ctx.strokeRect(-26, -26, 52, 52);
    ctx.restore();
    let x = 30;                                                        // barcode
    while (x < 230) {
      const w = 1 + Math.floor(rand() * 4);
      ctx.fillStyle = ink(0.1);
      ctx.fillRect(x, oy + 195, w, 40);
      x += w + 1 + Math.floor(rand() * 3);
    }
  }
}

// brushed steel: fine streaks all in one direction
function paintBrushed(ctx, mode, seed) {
  const rand = rng(seed), albedo = mode === 'albedo';
  ctx.fillStyle = gray(albedo ? 0.69 : 0.5);
  ctx.fillRect(0, 0, SIZE, SIZE);
  for (let i = 0; i < 900; i++) {
    const y = rand() * SIZE, x = rand() * SIZE, len = 60 + rand() * 260;
    ctx.strokeStyle = albedo ? gray(0.6 + rand() * 0.18, 0.5) : gray(0.42 + rand() * 0.16, 0.6);
    ctx.lineWidth = 1;
    wrapped(ctx, (ox, oy) => { ctx.beginPath(); ctx.moveTo(x + ox, y + oy); ctx.lineTo(x + ox + len, y + oy); ctx.stroke(); });
  }
}

// painted interior wall: very soft unevenness and faint scuffs low down
function paintWall(ctx, mode, seed) {
  const rand = rng(seed), albedo = mode === 'albedo';
  ctx.fillStyle = gray(albedo ? 0.69 : 0.5);
  ctx.fillRect(0, 0, SIZE, SIZE);
  paintNoise(ctx, albedo ? 0.015 : 0.06, rand);
  softBlobs(ctx, rand, 8, 60, 160, albedo ? 'rgba(0,0,0,0.035)' : 'rgba(0,0,0,0.04)');
  softBlobs(ctx, rand, 6, 40, 120, albedo ? 'rgba(255,255,255,0.04)' : 'rgba(255,255,255,0.04)');
  fineScratches(ctx, rand, 8, albedo ? 'rgba(0,0,0,0.05)' : 'rgba(60,60,60,0.2)', 40);
}

function makeTexture(paint, mode, seed, srgb) {
  const canvas = document.createElement('canvas');
  canvas.width = canvas.height = SIZE;
  paint(canvas.getContext('2d'), mode, seed);
  // A slight blur on the height map keeps the bump smooth instead of sparkly: hard one-pixel
  // edges in a height map turn into shimmering noise once they are lit. Drawn tiled so the
  // blur wraps around the edges.
  if (mode === 'height') {
    const soft = document.createElement('canvas');
    soft.width = soft.height = SIZE;
    const sctx = soft.getContext('2d');
    sctx.filter = 'blur(1.6px)';
    for (const ox of [-SIZE, 0, SIZE]) for (const oy of [-SIZE, 0, SIZE]) sctx.drawImage(canvas, ox, oy);
    canvas.getContext('2d').drawImage(soft, 0, 0);
  }
  const tex = new THREE.CanvasTexture(canvas);
  tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
  tex.anisotropy = 8;
  tex.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  tex.needsUpdate = true;
  return tex;
}

// Shared by every hub shader so one update moves all the flowing light
export const hubTime = { value: 0 };

export function createHubTextures() {
  return {
    plate: { albedo: makeTexture(paintPlate, 'albedo', 11, true), height: makeTexture(paintPlate, 'height', 11, false) },
    floor: { albedo: makeTexture(paintFloor, 'albedo', 23, true), height: makeTexture(paintFloor, 'height', 23, false) },
    paint: { albedo: makeTexture(paintPaint, 'albedo', 31, true), height: makeTexture(paintPaint, 'height', 31, false) },
    plastic: { albedo: makeTexture(paintPlastic, 'albedo', 37, true), height: makeTexture(paintPlastic, 'height', 37, false) },
    fabric: { albedo: makeTexture(paintFabric, 'albedo', 41, true), height: makeTexture(paintFabric, 'height', 41, false) },
    paper: { albedo: makeTexture(paintPaper, 'albedo', 43, true), height: makeTexture(paintPaper, 'height', 43, false) },
    label: { albedo: makeTexture(paintLabel, 'albedo', 47, true), height: makeTexture(paintLabel, 'height', 47, false) },
    brushed: { albedo: makeTexture(paintBrushed, 'albedo', 53, true), height: makeTexture(paintBrushed, 'height', 53, false) },
    wall: { albedo: makeTexture(paintWall, 'albedo', 59, true), height: makeTexture(paintWall, 'height', 59, false) }
  };
}

// Which texture each model material uses, and how big one tile is in metres
const SURFACES = {
  hull_light: { kind: 'plate', tile: 4.0, bump: 1.6 },
  hull_mid: { kind: 'plate', tile: 3.0, bump: 1.6 },
  hull_dark: { kind: 'plate', tile: 2.5, bump: 1.2 },
  trim: { kind: 'plate', tile: 1.5, bump: 1.2 },
  rust: { kind: 'plate', tile: 3.0, bump: 1.6 },
  pipe_black: { kind: 'plate', tile: 1.2, bump: 0.8 },
  accent: { kind: 'plate', tile: 2.0, bump: 0.6 },
  floor_dark: { kind: 'floor', tile: 4.0, bump: 1.2 },
  cont_red: { kind: 'plate', tile: 3.0, bump: 1.4 },
  cont_blue: { kind: 'plate', tile: 3.0, bump: 1.4 },
  cont_mustard: { kind: 'plate', tile: 3.0, bump: 1.4 },
  cont_grey: { kind: 'plate', tile: 3.0, bump: 1.4 },
  // the lab's furniture and objects: realistic surfaces
  navy: { kind: 'paint', tile: 0.7, bump: 0.35 },
  navy_light: { kind: 'paint', tile: 0.7, bump: 0.35 },
  soft_black: { kind: 'paint', tile: 0.6, bump: 0.35 },
  orange: { kind: 'paint', tile: 0.5, bump: 0.3 },
  lab_wall_low: { kind: 'paint', tile: 1.2, bump: 0.3 },
  smooth_white: { kind: 'plastic', tile: 0.45, bump: 0.25 },
  lab_blue: { kind: 'plastic', tile: 0.45, bump: 0.25 },
  whiteboard: { kind: 'plastic', tile: 1.0, bump: 0.1 },
  chair_fabric: { kind: 'fabric', tile: 0.06, bump: 1.0 },
  coat: { kind: 'fabric', tile: 0.05, bump: 0.8 },
  fabric: { kind: 'fabric', tile: 0.07, bump: 1.0 },
  fabric_light: { kind: 'fabric', tile: 0.07, bump: 1.0 },
  cushion_orange: { kind: 'fabric', tile: 0.06, bump: 1.0 },
  cushion_blue: { kind: 'fabric', tile: 0.06, bump: 1.0 },
  paper: { kind: 'paper', tile: 0.3, bump: 0 },
  label: { kind: 'label', tile: 0.16, bump: 0 },
  steel: { kind: 'brushed', tile: 0.3, bump: 0.4 },
  lab_wall: { kind: 'wall', tile: 2.2, bump: 0.25 }
};

// How the light flows in each glowing material (GLSL expression giving a multiplier)
const GLOWS = {
  blue_glow: 'vec3 f = vec3(1.0);',
  white_glow: 'vec3 f = vec3(1.0);',
  tile_glow: 'vec3 f = vec3(1.0);',
  lamp_warm: 'vec3 f = vec3(1.0);',
  // electrified water: a slow ripple of light (no flicker)
  water: 'vec3 f = vec3(0.8 + 0.2 * sin(vTriPos.x * 1.3 + uHubTime * 1.4) * sin(vTriPos.z * 1.1 - uHubTime));',
  hazard: 'vec3 f = vec3(1.0);',
  core_energy: 'vec3 f = vec3(0.45 + 0.55 * pow(0.5 + 0.5 * sin(vTriPos.y * 1.1 - uHubTime * 5.0), 2.0));',
  door_a_glow: 'vec3 f = vec3(1.0);',
  door_b_glow: 'vec3 f = vec3(1.0);',
  door_c_glow: 'vec3 f = vec3(1.0);',
  accent_glow: 'vec3 f = vec3(1.0);',
  aria_screen: 'vec3 f = vec3(1.0);'
};

const POS_VARYING = '\nvarying vec3 vTriPos;\nvarying vec3 vTriNrm;\n';

function addVertexPosition(shader) {
  shader.vertexShader = shader.vertexShader
    .replace('#include <common>', `#include <common>${POS_VARYING}`)
    .replace('#include <begin_vertex>',
      '#include <begin_vertex>\n  vTriPos = (modelMatrix * vec4(transformed, 1.0)).xyz;\n  vTriNrm = normalize(mat3(modelMatrix) * objectNormal);');
}

// Turn one of the model's materials into its textured, bump-mapped version
function texturedMaterial(source, spec, textures) {
  const mat = new THREE.MeshStandardMaterial({
    color: source.color.clone(),
    roughness: source.roughness,
    metalness: source.metalness,
    name: source.name
  });
  const tex = textures[spec.kind];
  mat.onBeforeCompile = (shader) => {
    shader.uniforms.uAlb = { value: tex.albedo };
    shader.uniforms.uHgt = { value: tex.height };
    shader.uniforms.uTile = { value: spec.tile };
    shader.uniforms.uBump = { value: spec.bump };
    addVertexPosition(shader);
    shader.fragmentShader = shader.fragmentShader
      .replace('#include <common>', `#include <common>${POS_VARYING}
        uniform sampler2D uAlb;
        uniform sampler2D uHgt;
        uniform float uTile;
        uniform float uBump;
        vec4 triSample(sampler2D t, vec3 p, vec3 w) {
          vec4 c = vec4(0.0);
          if (w.x > 0.02) c += texture2D(t, p.zy) * w.x;
          if (w.y > 0.02) c += texture2D(t, p.xz) * w.y;
          if (w.z > 0.02) c += texture2D(t, p.xy) * w.z;
          return c;
        }
        // Bends the normal by the slope of the height map (as three.js's own bump mapping does)
        vec3 triPerturb(vec3 surfPos, vec3 surfNorm, vec2 dHdxy, float faceDir) {
          vec3 sx = normalize(dFdx(surfPos));
          vec3 sy = normalize(dFdy(surfPos));
          vec3 r1 = cross(sy, surfNorm);
          vec3 r2 = cross(surfNorm, sx);
          float det = dot(sx, r1) * faceDir;
          vec3 grad = sign(det) * (dHdxy.x * r1 + dHdxy.y * r2);
          return normalize(abs(det) * surfNorm - grad);
        }`)
      .replace('#include <map_fragment>', `#include <map_fragment>
        vec3 triW = pow(abs(normalize(vTriNrm)), vec3(6.0));
        triW = max(triW - 0.02, 0.0);
        triW /= (triW.x + triW.y + triW.z);
        vec3 triP = vTriPos / uTile;
        vec3 triAlb = triSample(uAlb, triP, triW).rgb;
        float triH = triSample(uHgt, triP, triW).r;
        diffuseColor.rgb *= triAlb * 1.45;`)
      .replace('#include <roughnessmap_fragment>', `#include <roughnessmap_fragment>
        roughnessFactor = clamp(roughnessFactor * (1.55 - triH * 1.1), 0.12, 1.0);`)
      .replace('#include <normal_fragment_maps>', `#include <normal_fragment_maps>
        normal = triPerturb(-vViewPosition, normal, vec2(dFdx(triH), dFdy(triH)) * uBump, faceDirection);`);
  };
  return mat;
}

// Glowing materials keep their colour but their light flows
function glowingMaterial(source, flowGlsl) {
  const mat = source.clone();
  mat.onBeforeCompile = (shader) => {
    shader.uniforms.uHubTime = hubTime;
    addVertexPosition(shader);
    shader.fragmentShader = shader.fragmentShader
      .replace('#include <common>', `#include <common>${POS_VARYING}\nuniform float uHubTime;`)
      .replace('#include <emissivemap_fragment>', `#include <emissivemap_fragment>
        {
          ${flowGlsl}
          totalEmissiveRadiance *= f;
        }`);
  };
  return mat;
}

// Swaps the model's plain materials for the textured / flowing versions (in place)
export function applyHubMaterials(root, textures) {
  const cache = new Map();
  const swap = (m) => {
    if (cache.has(m)) return cache.get(m);
    let out = m;
    if (SURFACES[m.name]) out = texturedMaterial(m, SURFACES[m.name], textures);
    else if (GLOWS[m.name]) out = glowingMaterial(m, GLOWS[m.name]);
    cache.set(m, out);
    return out;
  };
  root.traverse((o) => {
    if (!o.isMesh) return;
    o.material = Array.isArray(o.material) ? o.material.map(swap) : swap(o.material);
  });
}
